INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P1', 'B', 'Continuous Integration contiene solo 3 etapas que son aquellas que se mencionan en el enunciado.');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P2', 'A', 'La clase con la anotación @Service contiene todas las operaciones relacionadas con la interacción con la base de datos.');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P3', 'D', 'Fueron 5 los aspectos mencionados en clase y uno de los más importantes de ellos fue la Justificación del Negocio');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P4', 'B', 'En la imagen del pipeline era la única que presentaba 4 etapas');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P5', 'C', '.');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P6', 'C', '.');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P7', 'A', '.');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P8', 'D', '.');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P9', 'B', '.');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P10', 'B', 'En la imagen del pipeline era la única que presentaba 5 etapas');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P11', 'C', '.');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P12', 'D', '.');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P13', 'B', '.');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P14', 'B', '.');
INSERT INTO SAMUEL_ROJAS (NUMERO, LETRA, ARGUMENTO) VALUES ('P15', 'C', '.');