INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('1', 'B', 'El CI va hasta las preubas de integracion, deplegar el artefacto');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('2', 'C', '@Repository');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('3', 'D', 'Organizacion, Justificacion del negocio, Calidad, Cambio, Riesgo');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('4', 'B', 'Continuous Delivery');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('5', 'C', 'Object Relational Mapping');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('6', 'C', 'ORM');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('7', 'A', 'Verdadero');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('8', 'D', 'Sprint');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('9', 'B', 'Falso');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('10', 'B', 'Continuous Deployment');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('11', 'D', 'Backlog');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('12', 'D', 'Control empirico del proceso, Autorganizacion, Priorizacion, Colaboracion,
Time-boxing, Desarrollo iterativo');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('13', 'B', 'DevOps');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('14', 'A', 'Verdadero');
INSERT INTO ALEXANDRA_CORTES (PREGUNTA, RESPUESTA, JUSTIFICACION) VALUES ('15', 'C', 'IaaS, SaaS, PaaS');