INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('1', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('2', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('3', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('4', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('5', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('6', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('7', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('8', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('9', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('10', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('11', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('12', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('13', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('14', '','');
INSERT INTO JUAN_VASQUEZ (PREGUNTA, RESPUESTA, ARGUMENTO) VALUES ('15', '','');


